### ISSUE TITLE
Incorrect offset for GUI particle effects when viewing recipes in EMI 

### ISSUE THREAD

**Issue by TheTrueYak** [SammySemicolon/Malum-Mod#246] opened 2024-06-21 22:45 UTC
When viewing recipes in EMI with items that use particle effects in the GUI, the particle effects will render all the way over on the far left side of the screen instead of where the actual item appears onscreen. Shown in the attached screenshot is a recipe viewed in EMI with items that have their particle effects way off to the side.
(1.6.0.2b-fabric)

![image](https://github.com/SammySemicolon/Malum-Mod/assets/107325508/8b990ff5-9148-4b93-99e0-ec82b594de17)

**Comment by yrsegal** [comment] 2024-06-22 13:39
Duplicate of #240

**Closed as completed by yrsegal** 2024-06-22 13:39 UTC
