### ISSUE TITLE
malum:magic_damage EvilCraft crash

### ISSUE THREAD

**Issue by dairymoose** [SammySemicolon/Malum-Mod#65] opened 2022-04-14 01:08 UTC
On a dedicated server it looks like running EvilCraft and Malum together causes a crash if the Vengeance Ring from evilcraft is enabled.  To reproduce the crash, enable the vengeance ring in evilcraft, equip it to a curio slot, and kill any mob to spawn a vengeance spirit.  It should crash soon after (you may have to swing at the vengeance spirit itself).

[21:04:16] [Server thread/ERROR]: Exception caught during firing event: Can't find attribute malum:magic_damage
	Index: 23
	Listeners:
		0: HIGHEST
		1: ASM: stepsword.mahoutsukai.handlers.ServerHandler@441862ac highPriorityLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		2: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@e6850cd onPlayerHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		3: NORMAL
		4: ASM: stepsword.mahoutsukai.handlers.ServerHandler@441862ac livingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		5: ASM: class vectorwing.farmersdelight.common.item.enchantment.BackstabbingEnchantment$BackstabbingEvent onKnifeBackstab(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$4044/0x0000000801696690@5f56cdb8
		7: ASM: class it.hurts.sskirillss.relics.items.relics.talisman.StellarCatalystItem$StellarCatalystServerEvents onEntityDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		8: ASM: class it.hurts.sskirillss.relics.items.relics.talisman.SoulDevourerItem$SoulDevourerServerEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		9: ASM: class it.hurts.sskirillss.relics.items.relics.talisman.ScarabTalismanItem$ScarabTalismanServerEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		10: ASM: class it.hurts.sskirillss.relics.items.relics.talisman.BlazingFlaskItem$BlazingFlaskServerEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		11: ASM: class it.hurts.sskirillss.relics.items.relics.ring.DelayRingItem$DelayRingEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		12: ASM: class it.hurts.sskirillss.relics.items.relics.necklace.ReflectionNecklaceItem$ReflectionNecklaceServerEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		13: ASM: class it.hurts.sskirillss.relics.items.relics.necklace.JellyfishNecklaceItem$JellyfishNecklaceEvents onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		14: ASM: class it.hurts.sskirillss.relics.items.relics.necklace.HolyLocketItem$HolyLocketEvents onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		15: ASM: class it.hurts.sskirillss.relics.items.relics.head.FragrantFlowerItem$FragrantFlowerServerEvents onEntityDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		16: ASM: class it.hurts.sskirillss.relics.items.relics.hands.WoolMittenItem$WoolMittenEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		17: ASM: class it.hurts.sskirillss.relics.items.relics.hands.RageGloveItem$RageGloveEvents onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		18: ASM: class it.hurts.sskirillss.relics.items.relics.feet.MagmaWalkerItem$MagmaWalkerServerEvents onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		19: ASM: class it.hurts.sskirillss.relics.items.relics.feet.IceSkatesItem$IceSkatesEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		20: ASM: class it.hurts.sskirillss.relics.items.relics.belt.HunterBeltItem$HunterBeltEvents onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		21: ASM: class it.hurts.sskirillss.relics.items.relics.belt.DrownedBeltItem$DrownedBeltServerEvents onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		22: ASM: class it.hurts.sskirillss.relics.items.relics.base.handlers.DurabilityHandler onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		23: ASM: class com.sammy.malum.core.eventhandlers.RuntimeEvents onHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		24: ASM: class com.github.klikli_dev.occultism.handlers.FamiliarEventHandler dodge(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		25: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@e6850cd onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		26: ASM: com.integral.etherium.core.EtheriumEventHandler@77402539 onEntityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		27: ASM: class com.teammetallurgy.aquaculture.misc.NeptunesMight onAttack(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		28: ASM: class com.hollingsworth.arsnouveau.common.potions.GravityEffect entityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		29: ASM: class com.hollingsworth.arsnouveau.common.event.ReactiveEvents livingHitEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		30: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler entityHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		31: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler livingHurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		32: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler playerDamaged(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		33: ASM: class com.mna.events.DamageEventHandler onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		34: net.minecraftforge.eventbus.EventBus$$Lambda$4044/0x0000000801696690@57869d06
		35: net.minecraftforge.eventbus.EventBus$$Lambda$4044/0x0000000801696690@3fd13c86
		36: net.minecraftforge.eventbus.EventBus$$Lambda$4044/0x0000000801696690@490fcc31
		37: net.minecraftforge.eventbus.EventBus$$Lambda$4044/0x0000000801696690@20ddf3a5
		38: ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@5ecae43b on(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		39: LOWEST
		40: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@e6850cd onLivingHurtFinal(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
		41: ASM: blusunrize.immersiveengineering.common.EventHandler@2b511151 onLivingHurt(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
java.lang.IllegalArgumentException: Can't find attribute malum:magic_damage
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22260_(AttributeSupplier.java:21)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.ai.attributes.AttributeSupplier.m_22245_(AttributeSupplier.java:28)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.ai.attributes.AttributeMap.m_22181_(AttributeMap.java:62)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_21133_(LivingEntity.java:1814)
	at TRANSFORMER/evilcraft@1.1.16/org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit.m_21133_(EntityVengeanceSpirit.java:166)
	at TRANSFORMER/malum@1.18.1-1.2.2/com.sammy.malum.core.eventhandlers.RuntimeEvents.onHurt(RuntimeEvents.java:127)
	at net.minecraftforge.eventbus.ASMEventHandler_572_RuntimeEvents_onHurt_LivingHurtEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.75/net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:324)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_6475_(Player.java:886)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1045)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_6469_(Player.java:821)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:664)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.Mob.m_7327_(Mob.java:1326)
	at TRANSFORMER/evilcraft@1.1.16/org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit.m_7327_(EntityVengeanceSpirit.java:263)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.ai.goal.MeleeAttackGoal.m_6739_(MeleeAttackGoal.java:147)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.ai.goal.MeleeAttackGoal.m_8037_(MeleeAttackGoal.java:138)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:110)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.Mob.m_6140_(Mob.java:698)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2502)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.Mob.m_8107_(Mob.java:495)
	at TRANSFORMER/evilcraft@1.1.16/org.cyclops.evilcraft.core.monster.EntityNoMob.m_8107_(EntityNoMob.java:51)
	at TRANSFORMER/evilcraft@1.1.16/org.cyclops.evilcraft.entity.monster.EntityVengeanceSpirit.m_8107_(EntityVengeanceSpirit.java:314)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2249)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.Mob.m_8119_(Mob.java:307)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:649)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.Level.m_46653_(Level.java:1056)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.1.0
	Mod List: 
		hexerei-0.1.14.jar                                |Hexerei                       |hexerei                       |0.1.14              |DONE      |Manifest: NOSIGNATURE
		CyclopsCore-1.18.1-1.13.2.jar                     |Cyclops Core                  |cyclopscore                   |1.13.2              |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		DungeonsMod-1.18-1.4.60.jar                       |Dungeons Mod                  |dungeonsmod                   |1.18-1.4.60         |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.18.1-1.3.3.jar                       |Blue Skies                    |blue_skies                    |1.3.3               |DONE      |Manifest: NOSIGNATURE
		tinyredstone-1.18-3.1.1.jar                       |Tiny Redstone                 |tinyredstone                  |1.18-3.1.1          |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.3.84.jar                           |Just Enough Items             |jei                           |9.2.3.84            |DONE      |Manifest: NOSIGNATURE
		IntegratedTerminals-1.18.1-1.2.16.jar             |IntegratedTerminals           |integratedterminals           |1.2.16              |DONE      |Manifest: NOSIGNATURE
		The_Graveyard_1.4_(FORGE)_for_1.18.1.jar          |The Graveyard                 |graveyard                     |1.4                 |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.18.1-2.4.2.jar                     |Doggy Talents 2               |doggytalents                  |2.4.2               |DONE      |Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.18.1-1.0.3.jar              |Library ferret                |libraryferret                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		BowInfinityFix-1.18.x-rv11.jar                    |Bow Infinity Fix              |bowinfinityfix                |1.18.x-rv11         |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.3.jar                  |Waystones                     |waystones                     |9.0.3               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.1-5.8.0beta15.jar                 |Journeymap                    |journeymap                    |5.8.0beta15         |DONE      |Manifest: NOSIGNATURE
		awesomedungeon-2.0.4.jar                          |Awesome Dungeon               |awesomedungeon                |2.0.4               |DONE      |Manifest: NOSIGNATURE
		modernlife-1.18.1-1.49.jar                        |Modern Life                   |modernlife                    |1.18.1-1.49         |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.10-1.18.jar                          |Citadel                       |citadel                       |1.10.10             |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.17.4.jar                              |Alex's Mobs                   |alexsmobs                     |1.17.4              |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.1-1.9.4-forge.jar             |Nature's Compass              |naturescompass                |1.18.1-1.9.4-forge  |DONE      |Manifest: NOSIGNATURE
		IntegratedREST-1.18.1-1.1.5.jar                   |IntegratedREST                |integratedrest                |1.1.5               |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.1-4.0.2.jar                        |Artifacts                     |artifacts                     |1.18.1-4.0.2        |DONE      |Manifest: NOSIGNATURE
		EvilCraft-1.18.1-1.1.16.jar                       |EvilCraft                     |evilcraft                     |1.1.16              |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.1.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.18.1-2.3.7.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.7               |DONE      |Manifest: NOSIGNATURE
		betteranimalsplus-1.18.1-11.0.3-forge.jar         |Better Animals Plus           |betteranimalsplus             |1.18.1-11.0.3       |DONE      |Manifest: NOSIGNATURE
		mahoutsukai-1.18.1-v1.34.0.jar                    |Mahou Tsukai                  |mahoutsukai                   |1.18.1-v1.34.0      |DONE      |Manifest: NOSIGNATURE
		balm-2.4.1+0.jar                                  |Balm                          |balm                          |2.4.1+0             |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.138.jar         |Just Enough Resources         |jeresources                   |0.13.1.138          |DONE      |Manifest: NOSIGNATURE
		Beyond-Earth-1.18.1-6.0d.jar                      |Beyond Earth                  |beyond_earth                  |6.0c                |DONE      |Manifest: NOSIGNATURE
		Uncrafter-1.18.1-1.0.0.jar                        |Uncrafter                     |uncrafter                     |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.1.50-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.50              |DONE      |Manifest: NOSIGNATURE
		toofast-1.18-0.0.1.2.jar                          |Too Fast                      |toofast                       |0.0.1.2             |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.1-1.1.9.jar                  |Supplementaries               |supplementaries               |1.1.9               |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.0.12_Fabric+Forge.jar                |Seed Fix + Terralith          |seedfix_forge                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.10.0.jar                         |Refined Storage               |refinedstorage                |1.10.0              |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.18.1-2.1.3.jar                    |Structure Gel API             |structure_gel                 |2.1.3               |DONE      |Manifest: NOSIGNATURE
		selene-1.18-1.12.0.jar                            |Selene                        |selene                        |1.18-1.12.0         |DONE      |Manifest: NOSIGNATURE
		ironchest-1.18-13.0.7.jar                         |Iron Chests                   |ironchest                     |1.18-13.0.7         |DONE      |Manifest: NOSIGNATURE
		IntegratedCrafting-1.18.1-1.0.21.jar              |IntegratedCrafting            |integratedcrafting            |1.0.21              |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.18.1-2.1.49d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.49d-1.18.1      |DONE      |Manifest: NOSIGNATURE
		server-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		Dynmap-3.3-beta-4-forge-1.18.jar                  |Dynmap                        |dynmap                        |3.3-beta-4-617      |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.1-1.1.0.73.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.73     |DONE      |Manifest: NOSIGNATURE
		CommonCapabilities-1.18.1-2.8.2.jar               |CommonCapabilities            |commoncapabilities            |2.8.2               |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.18.1-7.1.0-145.jar         |Immersive Engineering         |immersiveengineering          |1.18.1-7.1.0-145    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BiomesOPlenty-1.18.1-15.0.0.105-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.105   |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.1-4.4.1.jar                             |Jade                          |jade                          |4.4.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.75-universal.jar                |Forge                         |forge                         |39.0.75             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Botania-1.18.1-428.jar                            |Botania                       |botania                       |1.18.1-428          |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18.1-1.0.39-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.1-1.0.39-ALPHA |DONE      |Manifest: NOSIGNATURE
		spark-1.8.14-forge.jar                            |spark                         |spark                         |1.8.14              |DONE      |Manifest: NOSIGNATURE
		doggychunks-1.18.1-1.0.jar                        |Doggy Chunks                  |doggychunks                   |1.18.1-1.0          |DONE      |Manifest: NOSIGNATURE
		TelePass-1.18-1.1.2.jar                           |Telepass                      |telepass                      |1.1.2               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.0.jar                     |Flywheel                      |flywheel                      |1.18-0.6.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4d.jar                         |Create                        |create                        |0.4d                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.2.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.2      |DONE      |Manifest: NOSIGNATURE
		CuriosQuarkOBP-1.18.1-1.1.0.jar                   |Curios Quark Oddities Backpack|curiosquarkobp                |1.1.0               |DONE      |Manifest: NOSIGNATURE
		relics-0.3.4.1.jar                                |Relics                        |relics                        |0.3.4.1             |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.1-64.jar                           |Patchouli                     |patchouli                     |1.18.1-64           |DONE      |Manifest: NOSIGNATURE
		blockui-1.18.1-0.0.43-ALPHA.jar                   |UI Library Mod                |blockui                       |1.18.1-0.0.43-ALPHA |DONE      |Manifest: NOSIGNATURE
		IntegratedDynamics-1.18.1-1.10.12.jar             |IntegratedDynamics            |integrateddynamics            |1.10.12             |DONE      |Manifest: NOSIGNATURE
		tooslow-1.18.1-1.0.jar                            |You're Too Slow               |tooslow                       |1.18.1-1.0          |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18-FORGE-1.8.3.jar                    |Croptopia                     |croptopia                     |1.8.3               |DONE      |Manifest: NOSIGNATURE
		malum-1.18.1-1.2.2.jar                            |Malum                         |malum                         |1.18.1-1.2.2        |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.1-0.36.jar                   |Polymorph                     |polymorph                     |1.18.1-0.36         |DONE      |Manifest: NOSIGNATURE
		corail_recycler-5.5.0-1.18.1.jar                  |Corail Recycler               |corail_recycler               |5.5.0               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		Quark-3.1-340.jar                                 |Quark                         |quark                         |3.1-340             |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.1.jar                  |Storage Drawers               |storagedrawers                |10.1.1              |DONE      |Manifest: NOSIGNATURE
		mna-1.7.0.4.jar                                   |Mana and Artifice             |mna                           |1.7.0.4             |DONE      |Manifest: NOSIGNATURE
		IntegratedTunnels-1.18.1-1.8.11.jar               |IntegratedTunnels             |integratedtunnels             |1.8.11              |DONE      |Manifest: NOSIGNATURE
		structurize-1.18.1-1.0.346-ALPHA.jar              |Structurize                   |structurize                   |1.18.1-1.0.346-ALPHA|DONE      |Manifest: NOSIGNATURE
		multi-piston-1.18-1.2.2-ALPHA.jar                 |Multi-Piston                  |multipiston                   |1.18-1.2.2-ALPHA    |DONE      |Manifest: NOSIGNATURE
		EnigmaticLegacy-2.17.3.jar                        |Enigmatic Legacy              |enigmaticlegacy               |2.17.3              |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.18.1-1.0.448-ALPHA.jar             |MineColonies                  |minecolonies                  |1.18.1-1.0.448-ALPHA|DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		architectury-3.4.9.jar                            |Architectury                  |architectury                  |3.4.9               |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |4.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		occultism-1.18.1-1.26.5.jar                       |Occultism                     |occultism                     |1.18.1-1.26.5       |DONE      |Manifest: NOSIGNATURE
		Oh+The+Biomes+You'll+Go-forge-1.18.1-1.3.5.8.jar  |Oh The Biomes You'll Go       |byg                           |1.3.5.8             |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.1-2.3.2.jar                      |Aquaculture 2                 |aquaculture                   |1.18.1-2.3.2        |DONE      |Manifest: NOSIGNATURE
		krypton-1.0.0.jar                                 |Krypton Reforged              |krypton                       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		observable-1.2.3-forge.jar                        |Observable                    |observable                    |1.2.3               |DONE      |Manifest: NOSIGNATURE
		expandability-5.0.0-forge.jar                     |ExpandAbility                 |expandability                 |5.0.0               |DONE      |Manifest: NOSIGNATURE
		exoticbirds-1.18.1-1.1.0.jar                      |Exotic Birds                  |exoticbirds                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-1.18.1-0.3.2.jar                   |Valhelsia Core                |valhelsia_core                |1.18.1-0.3.2        |DONE      |Manifest: NOSIGNATURE
		forbidden_arcanus-1.18.1-2.0.2.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.18.1-2.0.2        |DONE      |Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.11.jar                    |GeckoLib                      |geckolib3                     |3.0.11              |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.18.1-2.2.2.jar                      |Ars Nouveau                   |ars_nouveau                   |2.2.2               |DONE      |Manifest: NOSIGNATURE
		corail_pillar-5.4.0-1.18.1.jar                    |Corail Pillar                 |corail_pillar                 |5.4.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d5912ccf-cf72-4bf3-a6f3-9266dd0af9cc
	FML: 39.0
	Forge: net.minecraftforge:39.0.75

**Comment by RealRTTV** [comment] 2022-04-14 01:30
sammy told me to tell you this has been fixed in the indev versions (https://github.com/SammySemicolon/Malum-Mod/tree/1.18.1-dev)

**Comment by isNaN** [comment] 2022-04-14 15:05
The indev-version that fixes this issue for you can be downloaded from here: https://www.mediafire.com/file/svh32z7jfiehw6z/malum-1.18.1-1.3.jar/file

A few more features are yet to be added before this is the official release of 1.3.

**Comment by SammySemicolon** [comment] 2022-04-15 11:25
As a note; this happens when malum damage calculations happen on some modded entities, not sure why or how and I can't reproduce it. Regardless, it'll be fixed in 1.3 as isNaN and rttv stated

**Closed as completed** 2022-04-15 11:24 UTC
